developerMode: true
exposeOptions:
  nodeService:
    type: ClusterIP
  broadcastOptions:
    clients:
      type: ServiceClusterIP
    nodes:
      type: ServiceClusterIP
sysctls:
  - "fs.aio-max-nr=4082080"
datacenter: validator
racks:
  - name: rack-1
    members: 3
    scyllaConfig: "scylla-config"
    storage:
      capacity: 2Gi
    resources:
      limits:
        cpu: 1
        memory: 2Gi
      requests:
        cpu: 1
        memory: 2Gi
